CREATE TABLE posts(
    id INT(16) NOT NULL,
    platformFacebook INT(1) NOT NULL,
    platformTwitter INT(1) NOT NULL,
    platformInstagram INT(1) NOT NULL,
    platformLinkedin INT(1) NOT NULL,
    postText VARCHAR(6256),
    postPhoto VARCHAR(1024),
    postDate VARCHAR(64) NOT NULL,
    postTimezone VARCHAR(256) NOT NULL,
    fbPerson VARCHAR(64),
    linkedin_business VARCHAR(64),
    appUser INT(6) NOT NULL,
    igUser VARCHAR(1024),
    igPassword VARCHAR(1024),
    fb_access_token VARCHAR(256),
    tw_oauth_token VARCHAR(256),
    tw_oauth_token_secret VARCHAR(256),
    li_access_token VARCHAR(256),
    li_access_token_expiresAt VARCHAR(256),
    published INT(1) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (appUser) REFERENCES users(id)
);
